# Generated by Django 5.1.3 on 2024-11-18 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('truck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_consumption_per_day', models.DecimalField(decimal_places=2, max_digits=4)),
                ('distance', models.FloatField(max_length=5)),
                ('color', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='truck.truckmodel')),
            ],
        ),
    ]
